In [5]:
import numpy as np
# NUmpy Stands for Numerical python and is the core library for numeric and scientific computing

In [7]:
l1 = [1,2,3,4]
n2 = np.array(l1)
n1 + n2

array([11, 22, 33, 44])

In [8]:
n3 = np.array([[1,2,3,4],[1,2,3,4]])
n3

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# zeros

In [10]:
n4 = np.zeros((4,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
n6 = np.full((3,4),7)
n6

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

# Arange

In [13]:
n= numpy.arange(20)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Random

In [15]:
n9 = np.random.randint(1,100,5)
n9

array([12, 13, 14, 49, 30])

# reshape

In [14]:
n.reshape(8, 8) # 8*8 = 64

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [15]:
n.reshape(4, 4, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

# array join, vstack, hstack, column_stack

In [16]:
n11= np.array([10,20,30])
n12 = np.array([40,50,60])

n13vstack = np.vstack((n11,n12))
n13vstack

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
n13hstack= np.hstack((n11,n12))
n13hstack

array([10, 20, 30, 40, 50, 60])

In [18]:
n13column_stack = np.column_stack((n11,n12))
n13column_stack

array([[10, 40],
       [20, 50],
       [30, 60]])

# intersection and difference

In [19]:
n14 = np.array([10,20,30,40,50,60])
n15 = np.array([50,60,70,80])

np.intersect1d(n14,n15)

array([50, 60])

In [20]:
np.setdiff1d(n14,n15)

array([10, 20, 30, 40])

In [21]:
np.setdiff1d(n15,n14)

array([70, 80])

## converting images to numpy array

In [22]:
import cv2

In [26]:
im_g = cv2.imread('smallgray.png', 0) # grayscale
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
im_g = cv2.imread('smallgray.png', 1) #bgr
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

## writing an image

In [32]:
cv2.imwrite('s_new_image.png',im_g)

## indexing, slicing and iterating numpy Arrays

In [37]:
im_g = cv2.imread('smallgray.png',0)

In [38]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [40]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [41]:
im_g[0:2,0:2]

array([[187, 158],
       [198, 125]], dtype=uint8)

In [44]:
im_g[:,0:3]

array([[187, 158, 104],
       [198, 125, 255],
       [209, 134, 255]], dtype=uint8)

## iterating numpy array

In [46]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [47]:
for i in im_g.T: # transpose
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [49]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


## Stacking and spliting numpy arrays

In [53]:
ims1 = numpy.hstack((im_g,im_g)) # horizontal
ims1

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [54]:
ims2 = numpy.vstack((im_g,im_g)) # vertical
ims2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [58]:
lst1 = numpy.hsplit(ims2.T,3)
lst1

[array([[187, 198],
        [158, 125],
        [104, 255],
        [121, 255],
        [143, 147]], dtype=uint8),
 array([[209, 187],
        [134, 158],
        [255, 104],
        [ 97, 121],
        [182, 143]], dtype=uint8),
 array([[198, 209],
        [125, 134],
        [255, 255],
        [255,  97],
        [147, 182]], dtype=uint8)]

In [59]:
lst = numpy.vsplit(ims2,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]